<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbb1fb4fdfebc02a4ba354b88c6085f6b
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbb1fb4fdfebc02a4ba354b88c6085f6b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbb1fb4fdfebc02a4ba354b88c6085f6b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
